"""Behavior classifier: predicts an employee's response from observable features.

Trained on interactions generated by the simulator (employee_simulator.py).
This is a SIMULATED behavior model, not a predictor of real human behavior.
Features are deliberately observable-only: role, department, alertness,
tactic, difficulty, and history signals. The hidden susceptibility profile
is never an input, so the model cannot trivially decode the ground truth.

Usage:
    python classifier.py train             # generate data, fit, save, report fidelity
    python classifier.py eval              # reload saved model and re-report
"""

import argparse
import hashlib
import json
import math
import random
import time
from pathlib import Path
from typing import List, Optional

import joblib
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix, f1_score
from sklearn.model_selection import train_test_split

from employee_simulator import (
    DEPARTMENTS,
    ROLES,
    TACTICS,
    generate_population,
    sample_response,
)
from reward import RESPONSES

MODELS_DIR = Path(__file__).resolve().parent / "models"
MODEL_PATH = MODELS_DIR / "behavior_model.pkl"

CLASSES = list(RESPONSES)
HISTORY_STATES = ("none",) + tuple(CLASSES)

# deterministic identity universe: the 100 generated employees
IDENTITY_CODES = tuple(e.code for e in generate_population(seed=42))


def one_hot(value: str, categories: tuple) -> List[float]:
    return [1.0 if value == category else 0.0 for category in categories]


def features_for(tactic: str, difficulty: int, role: str, department: str,
                 base_alertness: float, times_seen_tactic: int,
                 last_response: Optional[str], safe_streak: int,
                 round_no: int, employee_code: str = "emp_000") -> List[float]:
    """Observable-only feature vector for one scenario presentation.

    Includes employee identity and identity x tactic interactions so the
    model can represent per-employee-per-tactic tendencies (the hidden
    susceptibility signal) WITHOUT receiving the susceptibility values.
    """
    identity = one_hot(employee_code, IDENTITY_CODES)
    return (
        one_hot(tactic, TACTICS)
        + [difficulty / 5.0]
        + one_hot(role, ROLES)
        + one_hot(department, DEPARTMENTS)
        + [base_alertness]
        + [math.log1p(times_seen_tactic) / 5.0]
        + one_hot(last_response or "none", HISTORY_STATES)
        + [min(safe_streak, 10) / 10.0]
        + [math.log1p(round_no) / 10.0]
        + identity
        + tactic_identity(identity, tactic)
    )


def tactic_identity(identity: List[float], tactic: str) -> List[float]:
    """identity x tactic interaction block: 4 blocks of len(identity),
    only the block matching `tactic` is nonzero."""
    blocks = []
    for other in TACTICS:
        if other == tactic:
            blocks.extend(identity)
        else:
            blocks.extend([0.0] * len(identity))
    return blocks


def feature_names() -> List[str]:
    return (
        [f"tactic_{t}" for t in TACTICS]
        + ["difficulty"]
        + [f"role_{r}" for r in ROLES]
        + [f"dept_{d}" for d in DEPARTMENTS]
        + ["base_alertness", "log_times_seen"]
        + [f"last_{s}" for s in HISTORY_STATES]
        + ["safe_streak", "log_round"]
        + [f"id_{c}" for c in IDENTITY_CODES]
        + [f"id_{c}__tactic_{t}" for t in TACTICS for c in IDENTITY_CODES]
    )


def generate_training_data(n_employees: int = 100, rounds_per_employee: int = 500,
                           seed: int = 42) -> tuple:
    """Sample labeled interactions by playing random-tactic sessions."""
    rng = random.Random(seed)
    population = generate_population(seed=seed)[:n_employees]
    features, labels = [], []
    for emp in population:
        times_seen = {tactic: 0 for tactic in TACTICS}
        last_response = None
        safe_streak = 0
        for round_no in range(1, rounds_per_employee + 1):
            tactic = rng.choice(TACTICS)
            difficulty = 3
            response = sample_response(emp, tactic, difficulty, rng=rng)
            features.append(features_for(
                tactic, difficulty, emp.role, emp.department, emp.base_alertness,
                times_seen[tactic], last_response, safe_streak, round_no,
                employee_code=emp.code))
            labels.append(response)
            times_seen[tactic] += 1
            last_response = response
            safe_streak = safe_streak + 1 if response in ("ignore", "report") else 0
    return features, labels


def fidelity_metrics(model, X_test: list, y_test: list) -> dict:
    """Accuracy, macro-F1, confusion matrix vs the simulator's ground truth."""
    predictions = model.predict(X_test)
    return {
        "accuracy": accuracy_score(y_test, predictions),
        "macro_f1": f1_score(y_test, predictions, average="macro"),
        "confusion_matrix": confusion_matrix(y_test, predictions, labels=CLASSES).tolist(),
        "n_test": len(y_test),
    }


def train_and_save(n_employees: int = 100, rounds_per_employee: int = 500,
                   seed: int = 42, test_size: float = 0.2,
                   output_path: Path = MODEL_PATH) -> dict:
    """Generate data, fit a multinomial logistic regression, save artifact."""
    features, labels = generate_training_data(n_employees, rounds_per_employee, seed)
    X_train, X_test, y_train, y_test = train_test_split(
        features, labels, test_size=test_size, random_state=seed, stratify=labels)

    model = LogisticRegression(solver="lbfgs", max_iter=2000)
    model.fit(X_train, y_train)

    metrics = fidelity_metrics(model, X_test, y_test)
    artifact = {
        "model": model,
        "classes": CLASSES,
        "feature_count": len(features[0]),
        "n_samples": len(features),
        "n_employees": n_employees,
        "rounds_per_employee": rounds_per_employee,
        "seed": seed,
        "metrics": {k: v for k, v in metrics.items() if k != "confusion_matrix"},
        "confusion_matrix": metrics["confusion_matrix"],
        "trained_at": time.strftime("%Y-%m-%dT%H:%M:%S"),
    }
    MODELS_DIR.mkdir(exist_ok=True)
    joblib.dump(artifact, output_path)
    return artifact


def model_fingerprint(artifact: dict) -> str:
    return hashlib.sha256(json.dumps(
        artifact["metrics"], sort_keys=True).encode()).hexdigest()[:12]


class BehaviorClassifier:
    """Loads the saved artifact and predicts responses from a feature dict."""

    def __init__(self, path: Path = MODEL_PATH):
        if not Path(path).exists():
            raise FileNotFoundError(f"no trained model at {path}; run `python classifier.py train`")
        artifact = joblib.load(path)
        self.model = artifact["model"]
        self.classes = artifact["classes"]
        self.info = {
            "n_samples": artifact["n_samples"],
            "n_employees": artifact["n_employees"],
            "feature_count": artifact["feature_count"],
            "accuracy": artifact["metrics"]["accuracy"],
            "macro_f1": artifact["metrics"]["macro_f1"],
            "fingerprint": model_fingerprint(artifact),
            "trained_at": artifact["trained_at"],
            "path": str(path),
        }

    def predict(self, features: dict) -> dict:
        """features must contain the keys consumed by features_for()."""
        vector = features_for(**features)
        probabilities = self.model.predict_proba([vector])[0]
        classes = [str(c) for c in self.model.classes_]
        prediction = str(self.model.predict([vector])[0])
        return {
            "probs": {cls: float(prob) for cls, prob in zip(classes, probabilities)},
            "predicted": prediction,
        }


def report(artifact: dict) -> None:
    print("Fidelity of the simulated behavior classifier vs the simulator oracle:")
    print(f"  accuracy   : {artifact['metrics']['accuracy']:.3f}")
    print(f"  macro-F1   : {artifact['metrics']['macro_f1']:.3f}")
    print(f"  samples    : {artifact['n_samples']} ({artifact['n_employees']} employees x "
          f"{artifact['rounds_per_employee']} rounds, seed {artifact['seed']})")
    print("  confusion matrix (rows=true, cols=predicted):")
    header = "      " + "".join(f"{cls[:9]:>10}" for cls in CLASSES)
    print(header)
    for row, cls in zip(artifact["confusion_matrix"], CLASSES):
        print(f"  {cls[:9]:>7}" + "".join(f"{count:>10}" for count in row))
    print(f"  artifact -> {MODEL_PATH}")


def main() -> None:
    parser = argparse.ArgumentParser(description="Train/evaluate the simulated behavior classifier")
    parser.add_argument("command", choices=("train", "eval"))
    parser.add_argument("--employees", type=int, default=100)
    parser.add_argument("--rounds", type=int, default=500)
    parser.add_argument("--seed", type=int, default=42)
    args = parser.parse_args()

    if args.command == "train":
        artifact = train_and_save(args.employees, args.rounds, args.seed)
    else:
        artifact = joblib.load(MODEL_PATH)
    report(artifact)


if __name__ == "__main__":
    main()